# Generated by Django 3.2.1 on 2022-11-11 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_roommore'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommore',
            name='winner_amount',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='roommore',
            name='winner_name',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='roommore',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='roommore',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
