# Generated by Django 3.1.13 on 2023-03-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230313_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='roommore',
            name='owner',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
