# Generated by Django 3.1.13 on 2022-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.Field(primary_key=True, serialize=False),
        ),
    ]
