# Generated by Django 3.1.13 on 2022-11-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20221107_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='ids',
            new_name='id',
        ),
    ]
