# Generated by Django 3.1.13 on 2022-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_auto_20221107_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
