# Generated by Django 3.1.13 on 2022-11-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_auto_20221107_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='pid',
            new_name='id',
        ),
    ]
