# Generated by Django 4.2.1 on 2023-05-06 12:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0004_forum_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
