# Generated by Django 4.2.1 on 2023-05-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0005_alter_forum_description_alter_replies_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='email',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
