# Generated by Django 4.2.1 on 2023-05-14 05:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0007_alter_forum_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='replies',
            name='answer',
            field=tinymce.models.HTMLField(default='null'),
            preserve_default=False,
        ),
    ]
