# Generated by Django 4.2.1 on 2023-05-14 05:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0008_alter_forum_description_alter_replies_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='replies',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
