# Generated by Django 4.2.1 on 2023-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0009_alter_forum_description_alter_replies_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
