# Generated by Django 4.2.1 on 2023-05-14 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0010_alter_forum_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
